import {
  IRModule, IRDecl, IRStmt, IRExpr,
  IRFuncDecl, IRVarDecl, IRExprStmt, IRIf, IRForRange, IRForEach,
  IRLoop, IRBreak, IRReturn, IRSet, IRThrow, IRTry,
  IRLiteral, IRGet, IRCall, IRBuiltinCall, IRBinOp, IRUnaryOp,
  IRBlockLiteral, IRFieldGet, IRFieldSet, IRMakeContext, IRMakeClosure, IRNone,
} from './ir';

// ============================================================
// Lua 5.1 Code Emitter
// ============================================================

// Runtime chunks that are conditionally included
type RuntimeChunk = 'parse' | 'to' | 'make' | 'require' | 'type-predicates';

const RUNTIME_WARNINGS: Record<RuntimeChunk, string> = {
  'parse': 'parse requires a runtime for your chosen target. Output size will be bigger than normal.',
  'to': 'to requires a runtime for your chosen target. Output size will be bigger than normal.',
  'make': 'make requires a runtime for your chosen target. Output size will be bigger than normal.',
  'require': 'require requires a runtime for your chosen target. Output size will be bigger than normal.',
  'type-predicates': 'type predicates (integer?, string?, etc.) require a runtime for your chosen target. Output size will be bigger than normal.',
};

// Module-level state for the current compilation
let neededRuntime: Set<RuntimeChunk>;
let emitWarnings: string[];

export type EmitResult = { code: string; warnings: string[] };

export function emitLua(mod: IRModule): EmitResult {
  neededRuntime = new Set();
  emitWarnings = [];

  // Emit declarations first to discover runtime needs
  const declLines: string[] = [];
  for (const decl of mod.declarations) {
    declLines.push(emitDecl(decl, 0));
  }

  // Build output
  const lines: string[] = [];
  lines.push(`-- Generated by Kintsugi/Lua compiler`);
  lines.push(`-- Module: ${mod.name || 'main'}`);
  lines.push('');

  // Always-included prelude
  lines.push(LUA_PRELUDE);
  lines.push('');

  // Conditional runtime chunks
  for (const chunk of neededRuntime) {
    lines.push(RUNTIME_CHUNKS[chunk]);
    lines.push('');
  }

  // Declarations
  for (const line of declLines) {
    lines.push(line);
  }

  // Exports
  if (mod.exports.length > 0) {
    lines.push('');
    lines.push('return {');
    for (const name of mod.exports) {
      lines.push(`  ${luaName(name)} = ${luaName(name)},`);
    }
    lines.push('}');
  }

  // Collect warnings
  for (const chunk of neededRuntime) {
    emitWarnings.push(`WARNING: ${RUNTIME_WARNINGS[chunk]}`);
  }

  return { code: lines.join('\n'), warnings: emitWarnings };
}

// ============================================================
// Declaration emission
// ============================================================

function emitDecl(decl: IRDecl, indent: number): string {
  switch (decl.tag) {
    case 'func':
      return emitFunc(decl, indent);
    case 'var':
      return emitVar(decl, indent);
    default:
      return emitStmt(decl as IRStmt, indent);
  }
}

function emitFunc(decl: IRFuncDecl, indent: number): string {
  const pad = '  '.repeat(indent);
  const params = decl.params.map(p => luaName(p.name)).join(', ');
  const lines: string[] = [];

  lines.push(`${pad}local function ${luaName(decl.name)}(${params})`);

  // Emit body, adding implicit return on last expression or if/either
  const body = decl.body;
  for (let i = 0; i < body.length; i++) {
    const stmt = body[i];
    if (i === body.length - 1 && stmt.tag === 'expr') {
      lines.push(`${pad}  return ${emitExpr(stmt.expr)}`);
    } else if (i === body.length - 1 && stmt.tag === 'if') {
      lines.push(emitIfWithReturn(stmt, indent + 1));
    } else {
      lines.push(emitStmt(stmt, indent + 1));
    }
  }

  lines.push(`${pad}end`);
  lines.push('');

  return lines.join('\n');
}

function emitVar(decl: IRVarDecl, indent: number): string {
  const pad = '  '.repeat(indent);
  return `${pad}local ${luaName(decl.name)} = ${emitExpr(decl.value)}`;
}

// ============================================================
// Statement emission
// ============================================================

function emitStmt(stmt: IRStmt, indent: number): string {
  const pad = '  '.repeat(indent);

  switch (stmt.tag) {
    case 'set':
      return `${pad}${luaName(stmt.name)} = ${emitExpr(stmt.value)}`;

    case 'return':
      return `${pad}return ${emitExpr(stmt.value)}`;

    case 'if': {
      const lines: string[] = [];
      lines.push(`${pad}if ${emitExpr(stmt.condition)} then`);
      for (const s of stmt.then) lines.push(emitStmt(s, indent + 1));
      if (stmt.else) {
        if (stmt.else.length === 1 && stmt.else[0].tag === 'if') {
          lines.push(`${pad}else`);
          for (const s of stmt.else) lines.push(emitStmt(s, indent + 1));
        } else {
          lines.push(`${pad}else`);
          for (const s of stmt.else) lines.push(emitStmt(s, indent + 1));
        }
      }
      lines.push(`${pad}end`);
      return lines.join('\n');
    }

    case 'loop': {
      const lines: string[] = [];
      lines.push(`${pad}while true do`);
      for (const s of stmt.body) lines.push(emitStmt(s, indent + 1));
      lines.push(`${pad}end`);
      return lines.join('\n');
    }

    case 'for-range': {
      const lines: string[] = [];
      const varName = luaName(stmt.variable);
      lines.push(`${pad}for ${varName} = ${emitExpr(stmt.from)}, ${emitExpr(stmt.to)}, ${emitExpr(stmt.step)} do`);
      for (const s of stmt.body) lines.push(emitStmt(s, indent + 1));
      lines.push(`${pad}end`);
      return lines.join('\n');
    }

    case 'for-each': {
      const lines: string[] = [];
      if (stmt.stride === 1 && stmt.variables.length === 1) {
        const varName = luaName(stmt.variables[0].name);
        lines.push(`${pad}for _, ${varName} in ipairs(${emitExpr(stmt.source)}) do`);
      } else {
        const varNames = stmt.variables.map(v => luaName(v.name));
        lines.push(`${pad}for __i = 1, #${emitExpr(stmt.source)}, ${stmt.stride} do`);
        for (let j = 0; j < stmt.variables.length; j++) {
          lines.push(`${pad}  local ${varNames[j]} = ${emitExpr(stmt.source)}[__i + ${j}]`);
        }
      }
      for (const s of stmt.body) lines.push(emitStmt(s, indent + 1));
      lines.push(`${pad}end`);
      return lines.join('\n');
    }

    case 'break':
      return `${pad}break`;

    case 'expr':
      return `${pad}${emitExpr(stmt.expr)}`;

    case 'field-set':
      return `${pad}${emitExpr(stmt.target)}.${luaName(stmt.field)} = ${emitExpr(stmt.value)}`;

    case 'throw':
      return `${pad}error({kind = ${emitExpr(stmt.kind)}, message = ${emitExpr(stmt.message)}, data = ${emitExpr(stmt.data)}})`;

    case 'try': {
      const lines: string[] = [];
      lines.push(`${pad}local __ok, __err = pcall(function()`);
      for (const s of stmt.body) lines.push(emitStmt(s, indent + 1));
      lines.push(`${pad}end)`);
      if (stmt.handler) {
        lines.push(`${pad}if not __ok then`);
        lines.push(`${pad}  local ${luaName(stmt.handler.kindVar)} = __err.kind`);
        lines.push(`${pad}  local ${luaName(stmt.handler.messageVar)} = __err.message`);
        lines.push(`${pad}  local ${luaName(stmt.handler.dataVar)} = __err.data`);
        for (const s of stmt.handler.body) lines.push(emitStmt(s, indent + 1));
        lines.push(`${pad}end`);
      }
      if (stmt.finally) {
        for (const s of stmt.finally) lines.push(emitStmt(s, indent));
      }
      return lines.join('\n');
    }

    default:
      return `${pad}-- TODO: ${(stmt as any).tag}`;
  }
}

// ============================================================
// Expression emission
// ============================================================

function emitIfWithReturn(stmt: any, indent: number): string {
  const pad = '  '.repeat(indent);
  const lines: string[] = [];
  lines.push(`${pad}if ${emitExpr(stmt.condition)} then`);
  emitBranchWithReturn(stmt.then, indent + 1, lines);
  if (stmt.else) {
    if (stmt.else.length === 1 && stmt.else[0].tag === 'if') {
      lines.push(`${pad}else`);
      lines.push(emitIfWithReturn(stmt.else[0], indent + 1));
    } else {
      lines.push(`${pad}else`);
      emitBranchWithReturn(stmt.else, indent + 1, lines);
    }
  } else {
    lines.push(`${pad}else`);
    lines.push(`${'  '.repeat(indent + 1)}return nil`);
  }
  lines.push(`${pad}end`);
  return lines.join('\n');
}

function emitBranchWithReturn(stmts: any[], indent: number, lines: string[]): void {
  for (let i = 0; i < stmts.length; i++) {
    const s = stmts[i];
    if (i === stmts.length - 1) {
      if (s.tag === 'expr') {
        lines.push(`${'  '.repeat(indent)}return ${emitExpr(s.expr)}`);
      } else if (s.tag === 'if') {
        lines.push(emitIfWithReturn(s, indent));
      } else if (s.tag === 'return') {
        lines.push(emitStmt(s, indent));
      } else {
        lines.push(emitStmt(s, indent));
      }
    } else {
      lines.push(emitStmt(s, indent));
    }
  }
}

function emitExpr(expr: IRExpr): string {
  switch (expr.tag) {
    case 'literal':
      return emitLiteral(expr);

    case 'none':
      return 'nil';

    case 'get':
      return luaName(expr.name);

    case 'call':
      return `${typeof expr.func === 'string' ? luaName(expr.func) : emitExpr(expr.func)}(${expr.args.map(emitExpr).join(', ')})`;

    case 'builtin':
      return emitBuiltin(expr);

    case 'binop':
      return emitBinop(expr);

    case 'unary':
      if (expr.op === 'not') return `not ${emitExpr(expr.operand)}`;
      if (expr.op === 'negate') return `(-${emitExpr(expr.operand)})`;
      return emitExpr(expr.operand);

    case 'block':
      return `{${expr.values.map(emitExpr).join(', ')}}`;

    case 'index':
      return `${emitExpr(expr.target)}[${emitExpr(expr.position)}]`;

    case 'field-get':
      return `${emitExpr(expr.target)}.${luaName(expr.field)}`;

    case 'make-context': {
      const fields = expr.fields.map(f => `${luaName(f.name)} = ${emitExpr(f.value)}`);
      return `{${fields.join(', ')}}`;
    }

    case 'inline-if': {
      const condStr = emitExpr(expr.condition);
      const thenStmts = expr.then as any[];
      const elseStmts = expr.else as any[] | undefined;
      const lines: string[] = [];
      lines.push(`(function()`);
      lines.push(`    if ${condStr} then`);
      for (const s of thenStmts) {
        if (s === thenStmts[thenStmts.length - 1] && s.tag === 'expr') {
          lines.push(`      return ${emitExpr(s.expr)}`);
        } else if (s === thenStmts[thenStmts.length - 1] && s.tag === 'set') {
          lines.push(emitStmt(s, 3));
          lines.push(`      return ${luaName(s.name)}`);
        } else {
          lines.push(emitStmt(s, 3));
        }
      }
      if (elseStmts && elseStmts.length > 0) {
        lines.push(`    else`);
        for (const s of elseStmts) {
          if (s === elseStmts[elseStmts.length - 1] && s.tag === 'expr') {
            lines.push(`      return ${emitExpr(s.expr)}`);
          } else if (s === elseStmts[elseStmts.length - 1] && s.tag === 'set') {
            lines.push(emitStmt(s, 3));
            lines.push(`      return ${luaName(s.name)}`);
          } else {
            lines.push(emitStmt(s, 3));
          }
        }
      } else {
        lines.push(`    else`);
        lines.push(`      return nil`);
      }
      lines.push(`    end`);
      lines.push(`  end)()`);
      return lines.join('\n');
    }

    case 'make-closure': {
      const params = expr.params.map(p => luaName(p.name)).join(', ');
      const bodyStmts = expr.body;
      const bodyLines: string[] = [];
      for (let i = 0; i < bodyStmts.length; i++) {
        const s = bodyStmts[i];
        if (i === bodyStmts.length - 1 && s.tag === 'expr') {
          bodyLines.push(`    return ${emitExpr(s.expr)}`);
        } else {
          bodyLines.push(emitStmt(s, 2));
        }
      }
      return `function(${params})\n${bodyLines.join('\n')}\n  end`;
    }

    default:
      return `nil --[[ TODO: ${(expr as any).tag} ]]`;
  }
}

function emitLiteral(lit: IRLiteral): string {
  switch (lit.type) {
    case 'integer!':
    case 'float!':
      return String(lit.value);
    case 'string!':
      return `"${String(lit.value).replace(/\\/g, '\\\\').replace(/"/g, '\\"').replace(/\n/g, '\\n')}"`;
    case 'logic!':
      return lit.value ? 'true' : 'false';
    case 'char!':
      return `"${lit.value}"`;
    case 'lit-word!':
    case 'word!':
      return `"${lit.value}"`;
    default:
      return String(lit.value);
  }
}

function emitBinop(expr: IRBinOp): string {
  const left = emitExpr(expr.left);
  const right = emitExpr(expr.right);

  switch (expr.op) {
    case '+': return `(${left} + ${right})`;
    case '-': return `(${left} - ${right})`;
    case '*': return `(${left} * ${right})`;
    case '/': return `(${left} / ${right})`;
    case '%': return `(${left} % ${right})`;
    case '=': return `(${left} == ${right})`;
    case '<>': return `(${left} ~= ${right})`;
    case '<': return `(${left} < ${right})`;
    case '>': return `(${left} > ${right})`;
    case '<=': return `(${left} <= ${right})`;
    case '>=': return `(${left} >= ${right})`;
    case 'and': return `(${left} and ${right})`;
    case 'or': return `(${left} or ${right})`;
    default: return `(${left} ${expr.op} ${right})`;
  }
}

// ============================================================
// Builtin emission — request runtime chunks as needed
// ============================================================

function requireRuntime(chunk: RuntimeChunk): void {
  neededRuntime.add(chunk);
}

function emitBuiltin(expr: IRBuiltinCall): string {
  const args = expr.args.map(emitExpr);

  switch (expr.name) {
    // Always-available (in prelude)
    case 'print': return `print(${args[0]})`;
    case 'probe': return `__probe(${args[0]})`;
    case 'length?': return `#${args[0]}`;
    case 'empty?': return `(#${args[0]} == 0)`;
    case 'first': return `${args[0]}[1]`;
    case 'second': return `${args[0]}[2]`;
    case 'last': return `${args[0]}[#${args[0]}]`;
    case 'pick': return `${args[0]}[${args[1]}]`;
    case 'copy': return `__copy(${args[0]})`;
    case 'append': return `__append(${args[0]}, ${args[1]})`;
    case 'insert': return `table.insert(${args[0]}, ${args[2]}, ${args[1]})`;
    case 'remove': return `table.remove(${args[0]}, ${args[1]})`;
    case 'select': return `__select(${args[0]}, ${args[1]})`;
    case 'has?': return `__has(${args[0]}, ${args[1]})`;
    case 'index?': return `__index_of(${args[0]}, ${args[1]})`;
    case 'join': return `(tostring(${args[0]}) .. tostring(${args[1]}))`;
    case 'rejoin': return `__rejoin(${args[0]})`;
    case 'trim': return `__trim(${args[0]})`;
    case 'split': return `__split(${args[0]}, ${args[1]})`;
    case 'uppercase': return `string.upper(${args[0]})`;
    case 'lowercase': return `string.lower(${args[0]})`;
    case 'replace': return `string.gsub(${args[0]}, ${args[1]}, ${args[2]}, 1)`;
    case 'min': return `math.min(${args[0]}, ${args[1]})`;
    case 'max': return `math.max(${args[0]}, ${args[1]})`;
    case 'abs': return `math.abs(${args[0]})`;
    case 'negate': return `(-${args[0]})`;
    case 'round': return `__round(${args[0]})`;
    case 'odd?': return `(${args[0]} % 2 ~= 0)`;
    case 'even?': return `(${args[0]} % 2 == 0)`;
    case 'not': return `not ${args[0]}`;
    case 'type?': return `__type_of(${args[0]})`;
    case 'words-of': return `__words_of(${args[0]})`;
    case 'apply': return `__apply(${args[0]}, ${args[1]})`;
    case 'set': return `__set(${args[0]}, ${args[1]})`;
    case '__call_or_get': return `__call_or_get(${args[0]})`;

    // Runtime-requiring builtins
    case 'to':
      requireRuntime('to');
      return `__to(${args[0]}, ${args[1]})`;
    case 'make':
      requireRuntime('make');
      return `__make(${args[0]}, ${args[1]})`;
    case 'parse':
      requireRuntime('parse');
      return `__parse(${args[0]}, ${args[1]})`;
    case 'is?':
      requireRuntime('parse');
      return `__is_q(${args[0]}, ${args[1]})`;
    case 'require':
      requireRuntime('require');
      return `__require(${args[0]})`;
    case 'typeset':
      requireRuntime('type-predicates');
      return `__typeset(${args[0]})`;

    default: {
      // Type predicates: integer?, string?, etc.
      if (expr.name.endsWith('?') && expr.args.length === 1) {
        requireRuntime('type-predicates');
        return `__type_check(${args[0]}, "${expr.name.slice(0, -1)}!")`;
      }
      return `__builtin_${luaName(expr.name)}(${args.join(', ')})`;
    }
  }
}

// ============================================================
// Lua name sanitization
// ============================================================

function luaName(name: string): string {
  return name
    .replace(/\?$/, '_q')
    .replace(/!$/, '_b')
    .replace(/-/g, '_')
    .replace(/^#/, '_hash_');
}

// ============================================================
// Lua 5.1 runtime prelude — always included
// ============================================================

const LUA_PRELUDE = `-- Kintsugi runtime helpers (Lua 5.1)

local function __probe(v)
  print(tostring(v))
  return v
end

local function __copy(t)
  if type(t) == "string" then return t end
  local r = {}
  for i, v in ipairs(t) do r[i] = v end
  return r
end

local function __append(t, v)
  table.insert(t, v)
  return t
end

local function __select(t, key)
  if type(t) == "table" then
    for i = 1, #t - 1 do
      if t[i] == key then return t[i + 1] end
    end
    if t[key] ~= nil then return t[key] end
  end
  return nil
end

local function __has(t, v)
  if type(t) == "string" then
    return string.find(t, v, 1, true) ~= nil
  end
  for _, item in ipairs(t) do
    if item == v then return true end
  end
  return false
end

local function __index_of(t, v)
  if type(t) == "string" then
    local i = string.find(t, v, 1, true)
    return i
  end
  for i, item in ipairs(t) do
    if item == v then return i end
  end
  return nil
end

local function __rejoin(t)
  local parts = {}
  for _, v in ipairs(t) do
    parts[#parts + 1] = tostring(v)
  end
  return table.concat(parts)
end

local function __trim(s)
  return s:match("^%s*(.-)%s*$")
end

local function __split(s, delim)
  local result = {}
  for part in s:gmatch("([^" .. delim .. "]+)") do
    result[#result + 1] = part
  end
  return result
end

local function __round(n)
  return math.floor(n + 0.5)
end

local function __type_of(v)
  local t = type(v)
  if t == "number" then
    if v == math.floor(v) then return "integer!" end
    return "float!"
  elseif t == "string" then return "string!"
  elseif t == "boolean" then return "logic!"
  elseif t == "nil" then return "none!"
  elseif t == "table" then
    if v.__ktg_type then return v.__ktg_type end
    return "block!"
  elseif t == "function" then return "function!"
  end
  return "any!"
end

local function __call_or_get(v)
  if type(v) == "function" then return v() end
  return v
end

local function __words_of(ctx)
  local keys = {}
  for k, _ in pairs(ctx) do
    keys[#keys + 1] = k
  end
  return keys
end

local function __apply(fn, args)
  return fn(unpack(args))
end

local function __set(words, values)
  return values
end`;

// ============================================================
// Conditional runtime chunks
// ============================================================

const RUNTIME_CHUNKS: Record<RuntimeChunk, string> = {
  'to': `-- Runtime: type conversion
local function __to(target_type, value)
  local tn = target_type
  if type(target_type) == "table" and target_type.__ktg_type == "type!" then
    tn = target_type.name
  end
  if tn == "integer!" then
    if type(value) == "string" then return math.floor(tonumber(value) or 0) end
    if type(value) == "boolean" then return value and 1 or 0 end
    if type(value) == "number" then return math.floor(value) end
  elseif tn == "float!" then
    if type(value) == "string" then return (tonumber(value) or 0.0) + 0.0 end
    if type(value) == "number" then return value + 0.0 end
  elseif tn == "string!" then
    return tostring(value)
  elseif tn == "logic!" then
    return value ~= nil and value ~= false
  elseif tn == "block!" then
    if type(value) == "table" then return value end
    return {value}
  end
  error({kind = "type", message = "cannot convert to " .. tostring(tn), data = nil})
end`,

  'make': `-- Runtime: type construction
local function __make(target_type, spec)
  local tn = target_type
  if type(target_type) == "table" and target_type.__ktg_type == "type!" then
    tn = target_type.name
  end
  if tn == "map!" and type(spec) == "table" then
    local m = {}
    for i = 1, #spec - 1, 2 do
      m[tostring(spec[i])] = spec[i + 1]
    end
    m.__ktg_type = "map!"
    return m
  end
  if tn == "context!" and type(spec) == "table" then
    local ctx = {}
    for i = 1, #spec - 1, 2 do
      ctx[tostring(spec[i])] = spec[i + 1]
    end
    return ctx
  end
  error({kind = "type", message = "cannot make " .. tostring(tn), data = nil})
end`,

  'parse': `-- Runtime: parse engine
local __parse_char_classes = {
  alpha = function(ch) return ch:match("[%a]") ~= nil end,
  digit = function(ch) return ch:match("[%d]") ~= nil end,
  alnum = function(ch) return ch:match("[%w]") ~= nil end,
  space = function(ch) return ch:match("[%s]") ~= nil end,
  upper = function(ch) return ch:match("[%u]") ~= nil end,
  lower = function(ch) return ch:match("[%l]") ~= nil end,
}

local function __parse_split_on_pipe(rules)
  local alternatives = {}
  local current = {}
  for _, rule in ipairs(rules) do
    if rule == "|" then
      alternatives[#alternatives + 1] = current
      current = {}
    else
      current[#current + 1] = rule
    end
  end
  alternatives[#alternatives + 1] = current
  if #alternatives == 1 then return {rules} end
  return alternatives
end

local __parse_match_one, __parse_match_seq, __parse_match_seq_inner

function __parse_match_one(input, ipos, rules, rpos, captures, mode)
  local rule = rules[rpos]
  if not rule then return nil end
  if type(rule) == "table" then
    return __parse_match_seq(input, ipos, rule, 1, captures, mode)
  end
  if type(rule) == "string" then
    if mode == "string" then
      if input:sub(ipos, ipos + #rule - 1) == rule then return ipos + #rule end
    else
      if input[ipos] == rule then return ipos + 1 end
    end
    return nil
  end
  if rule == "skip" then
    if ipos <= #input then return ipos + 1 end
    return nil
  end
  if __parse_char_classes[rule] and mode == "string" then
    if ipos > #input then return nil end
    if __parse_char_classes[rule](input:sub(ipos, ipos)) then return ipos + 1 end
    return nil
  end
  return nil
end

function __parse_match_seq_inner(input, ipos, rules, rpos, captures, mode)
  while rpos <= #rules do
    local rule = rules[rpos]
    if type(rule) == "table" then
      local result = __parse_match_seq(input, ipos, rule, 1, captures, mode)
      if not result then return nil end
      ipos = result
      rpos = rpos + 1
    elseif type(rule) == "string" then
      if mode == "string" then
        if input:sub(ipos, ipos + #rule - 1) == rule then
          ipos = ipos + #rule
        else return nil end
      else
        if input[ipos] == rule then ipos = ipos + 1
        else return nil end
      end
      rpos = rpos + 1
    elseif rule == "skip" then
      if ipos > #input then return nil end
      ipos = ipos + 1
      rpos = rpos + 1
    elseif rule == "end" then
      if ipos > #input then rpos = rpos + 1 else return nil end
    elseif rule == "some" then
      rpos = rpos + 1
      local count = 0
      while true do
        local r = __parse_match_one(input, ipos, rules, rpos, captures, mode)
        if not r or r == ipos then break end
        ipos = r
        count = count + 1
      end
      if count == 0 then return nil end
      rpos = rpos + 1
    elseif rule == "any" then
      rpos = rpos + 1
      while true do
        local r = __parse_match_one(input, ipos, rules, rpos, captures, mode)
        if not r or r == ipos then break end
        ipos = r
      end
      rpos = rpos + 1
    elseif rule == "opt" then
      rpos = rpos + 1
      local r = __parse_match_one(input, ipos, rules, rpos, captures, mode)
      if r then ipos = r end
      rpos = rpos + 1
    elseif __parse_char_classes[rule] and mode == "string" then
      if ipos > #input then return nil end
      if __parse_char_classes[rule](input:sub(ipos, ipos)) then
        ipos = ipos + 1
      else return nil end
      rpos = rpos + 1
    else
      rpos = rpos + 1
    end
  end
  return ipos
end

function __parse_match_seq(input, ipos, rules, rpos, captures, mode)
  local alternatives = __parse_split_on_pipe(rules)
  if #alternatives > 1 then
    for _, alt in ipairs(alternatives) do
      local result = __parse_match_seq_inner(input, ipos, alt, 1, captures, mode)
      if result then return result end
    end
    return nil
  end
  return __parse_match_seq_inner(input, ipos, rules, rpos, captures, mode)
end

local function __parse(input, rules)
  local captures = {}
  local mode = type(input) == "string" and "string" or "block"
  local pos = __parse_match_seq(input, 1, rules, 1, captures, mode)
  if pos and pos > #input then return true end
  return false
end

local function __is_q(input, rules)
  return __parse(input, rules)
end`,

  'require': `-- Runtime: module loading
local __require_cache = {}
local function __require(path)
  if __require_cache[path] then return __require_cache[path] end
  local mod = dofile(path)
  __require_cache[path] = mod
  return mod
end`,

  'type-predicates': `-- Runtime: type predicates
local function __type_check(value, expected)
  local actual = __type_of(value)
  if expected == "function!" then
    return actual == "function!" or type(value) == "function"
  end
  return actual == expected
end

local function __typeset(types)
  return {__ktg_type = "typeset!", types = types}
end`,
};
