-- Generated by Kintsugi/Lua compiler
-- Module: main

-- Kintsugi runtime helpers (Lua 5.1)

local function __probe(v)
  print(tostring(v))
  return v
end

local function __copy(t)
  local r = {}
  for i, v in ipairs(t) do r[i] = v end
  return r
end

local function __append(t, v)
  table.insert(t, v)
  return t
end

local function __select(t, key)
  if type(t) == "table" then
    -- key-value pair lookup
    for i = 1, #t - 1 do
      if t[i] == key then return t[i + 1] end
    end
    -- also check hash part
    if t[key] ~= nil then return t[key] end
  end
  return nil
end

local function __has(t, v)
  if type(t) == "string" then
    return string.find(t, v, 1, true) ~= nil
  end
  for _, item in ipairs(t) do
    if item == v then return true end
  end
  return false
end

local function __index_of(t, v)
  if type(t) == "string" then
    local i = string.find(t, v, 1, true)
    return i
  end
  for i, item in ipairs(t) do
    if item == v then return i end
  end
  return nil
end

local function __rejoin(t)
  local parts = {}
  for _, v in ipairs(t) do
    parts[#parts + 1] = tostring(v)
  end
  return table.concat(parts)
end

local function __trim(s)
  return s:match("^%s*(.-)%s*$")
end

local function __split(s, delim)
  local result = {}
  for part in s:gmatch("([^" .. delim .. "]+)") do
    result[#result + 1] = part
  end
  return result
end

local function __round(n)
  return math.floor(n + 0.5)
end

print("Hello, Kintsugi!")
local x = 10
local y = 3
print((x + y))
print((x * y))
print(((2 + 3) * 4))
local function add(a, b)
  return (a + b)
end

print(add(3, 4))
local function fact(n)
  if (n == 0) then
    return 1
  end
  return (n * fact((n - 1)))
end

print(fact(10))
if (5 > 3) then
  print("yes")
else
  print("no")
end
for n = 1, 5, 1 do
  print(n)
end
local point = {x = 10, y = 20}
print(point.x)
print(point.y)
point.x = 99
print(point.x)
local function make_adder(n)
  return function(x)
    return (x + n)
  end
end

local add5 = make_adder(5)
print(add5(10))
print(string.upper("hello"))
print((tostring("hello") .. tostring(" world")))