-- Generated by Kintsugi/Lua compiler
-- Module: main

-- Kintsugi runtime helpers (Lua 5.1)

local function __probe(v)
  print(tostring(v))
  return v
end

local function __copy(t)
  local r = {}
  for i, v in ipairs(t) do r[i] = v end
  return r
end

local function __append(t, v)
  table.insert(t, v)
  return t
end

local function __select(t, key)
  if type(t) == "table" then
    -- key-value pair lookup
    for i = 1, #t - 1 do
      if t[i] == key then return t[i + 1] end
    end
    -- also check hash part
    if t[key] ~= nil then return t[key] end
  end
  return nil
end

local function __has(t, v)
  if type(t) == "string" then
    return string.find(t, v, 1, true) ~= nil
  end
  for _, item in ipairs(t) do
    if item == v then return true end
  end
  return false
end

local function __index_of(t, v)
  if type(t) == "string" then
    local i = string.find(t, v, 1, true)
    return i
  end
  for i, item in ipairs(t) do
    if item == v then return i end
  end
  return nil
end

local function __rejoin(t)
  local parts = {}
  for _, v in ipairs(t) do
    parts[#parts + 1] = tostring(v)
  end
  return table.concat(parts)
end

local function __trim(s)
  return s:match("^%s*(.-)%s*$")
end

local function __split(s, delim)
  local result = {}
  for part in s:gmatch("([^" .. delim .. "]+)") do
    result[#result + 1] = part
  end
  return result
end

local function __round(n)
  return math.floor(n + 0.5)
end

print("Hello, Kintsugi!")
local function add(a, b)
  (a + b)
end

print(__rejoin({"2 + 3 = ", nil}))
local squares = __builtin_loop({"for", nil, "from", 1, "to", 5, nil})
print(__rejoin({"Squares: ", "squares"}))
local function qsort(blk)
  if (#blk <= 1) then
    return blk
  end
  pivot = blk[1]
  rest = __copy(blk)
  table.remove(rest, 1)
  __set({"lo", "hi"}, __builtin_loop({"for", nil, "in", "rest", nil}))
  result = qsort(lo)
  __append(result, pivot)
  for _, x in ipairs(qsort(hi)) do
    __append(result, x)
  end
  result
end

print(__rejoin({"Sorted: ", "qsort", nil}))