-- Generated by Kintsugi/Lua compiler
-- Module: main

-- Kintsugi runtime helpers (Lua 5.1)

local function __probe(v)
  print(tostring(v))
  return v
end

local function __copy(t)
  local r = {}
  for i, v in ipairs(t) do r[i] = v end
  return r
end

local function __append(t, v)
  table.insert(t, v)
  return t
end

local function __select(t, key)
  if type(t) == "table" then
    -- key-value pair lookup
    for i = 1, #t - 1 do
      if t[i] == key then return t[i + 1] end
    end
    -- also check hash part
    if t[key] ~= nil then return t[key] end
  end
  return nil
end

local function __has(t, v)
  if type(t) == "string" then
    return string.find(t, v, 1, true) ~= nil
  end
  for _, item in ipairs(t) do
    if item == v then return true end
  end
  return false
end

local function __index_of(t, v)
  if type(t) == "string" then
    local i = string.find(t, v, 1, true)
    return i
  end
  for i, item in ipairs(t) do
    if item == v then return i end
  end
  return nil
end

local function __rejoin(t)
  local parts = {}
  for _, v in ipairs(t) do
    parts[#parts + 1] = tostring(v)
  end
  return table.concat(parts)
end

local function __trim(s)
  return s:match("^%s*(.-)%s*$")
end

local function __split(s, delim)
  local result = {}
  for part in s:gmatch("([^" .. delim .. "]+)") do
    result[#result + 1] = part
  end
  return result
end

local function __round(n)
  return math.floor(n + 0.5)
end

local function __call_or_get(v)
  if type(v) == "function" then return v() end
  return v
end

local x = 400
local y = 300
local speed = 200
love.load = function()
    return love.window.setTitle("Kintsugi + LOVE2D")
  end
love.update = function(dt)
    if love.keyboard.isDown("left") then
      x = (x - (speed * dt))
    end
    if love.keyboard.isDown("right") then
      x = (x + (speed * dt))
    end
    if love.keyboard.isDown("up") then
      y = (y - (speed * dt))
    end
    if love.keyboard.isDown("down") then
      y = (y + (speed * dt))
    end
  end
love.draw = function()
    love.graphics.setColor(1, 0.5, 0.2)
    love.graphics.circle("fill", x, y, 20)
    love.graphics.setColor(1, 1, 1)
    return love.graphics.print("Move with arrow keys", 10, 10)
  end